# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b20d9b45d5d2eed685e9b9f0a0450ab198e409aee63a8af314e181b1d3b1c7641113f9f17c8fa03f4c27ef699973eafc594f9a6d7131f7a2995323f393d0dd

test:
  secret_key_base: ce7e81f183e225099f169586c7eb2a5a5faa3b6596be5c2709df41e0a89ed1ed0b52b51ccff684eda8f89278ff103bacd1849ed532d0a5df49296ded5bf60764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
